app/Http/routes.php
    Route::get('update_employee_renumeration/{id}/{company_id}', 'HumanResourceController@update_employee_renumeration')->name('update_employee_renumeration');
    Route::post('update_employee_renumeration', 'HumanResourceController@update_employee_renumeration')->name('update_employee_renumeration');
    Route::get('add_employee_bonus', 'HumanResourceController@add_employee_bonus')->name('add_employee_bonus');
    Route::get('add_work_days', 'HumanResourceController@add_work_days')->name('add_work_days');
    Route::post('add_work_days', 'HumanResourceController@add_work_days')->name('add_work_days');
    Route::post('employee_bonus/{id}', 'HumanResourceController@employee_bonuses')->name('employee_bonus');
    Route::get('employee_deductions', 'HumanResourceController@employee_deductions')->name('employee_deductions');
//    Route::get('work_days', 'HumanResourceController@work_days')->name('work_days');

    Route::match(['get', 'post'], 'work_days', 'HumanResourceController@work_days')->name('work_days');


    Route::get('employee_renumerations', 'HumanResourceController@employee_renumerations')->name('employee_renumerations');
    Route::get('payslip/{employee_id}/{month}/{year}/{advance_company_uri}', 'HumanResourceController@payslip')->name('payslip');
    Route::get('download_payslip/{employee_id}/{month}/{year}', 'HumanResourceController@download_payslip')->name('download_payslip');
    Route::match(['get', 'post'], 'employee_absences', 'HumanResourceController@add_employee_absence')->name('employee_absences');
    Route::match(['get', 'post'], 'employee_loans', 'HumanResourceController@employee_loans')->name('employee_loans');
    // Route::get('employee_arrears', 'HumanResourceController@employee_arrears')->name('employee_arrears');
    Route::post('add_employee_deduction', 'HumanResourceController@add_employee_deduction')->name('add_employee_deduction');
    Route::get('add_employee_arrears', 'HumanResourceController@add_employee_arrears')->name('add_employee_arrears');
    // Route::post('add_employee_arrears', 'HumanResourceController@add_employee_arrears')->name('add_employee_arrears');
    Route::get('generate_payroll', 'HumanResourceController@generate_payroll')->name('generate_payroll');
    Route::post('generate_payroll', 'HumanResourceController@generate_payroll')->name('generate_payroll');
    Route::post('add_employee_absence', 'HumanResourceController@add_employee_absence')->name('add_employee_absence');
    Route::match(['get', 'post'], 'employee_arrears', 'HumanResourceController@employee_arrears')->name('employee_loans');
 
    // Route::post('add_employee_loan', 'HumanResourceController@add_employee_loan')->name('add_employee_loan');
    // Route::get('add_employee_loan', 'HumanResourceController@add_employee_loan')->name('add_employee_loan');
    Route::post('send_payslip', 'HumanResourceController@send_payslip')->name('send_payslip');
    Route::get('send_payslip', 'HumanResourceController@send_payslip')->name('send_payslip');
    Route::post('paye_report', 'ReportsController@paye_report')->name('paye_report');
    Route::get('paye_report', 'ReportsController@paye_report')->name('paye_report');
    Route::post('department_report', 'ReportsController@department_report')->name('department_report');
    Route::get('department_report', 'ReportsController@department_report')->name('department_report');
    Route::post('pension_report', 'ReportsController@pension_report')->name('pension_report');
    Route::get('pension_report', 'ReportsController@pension_report')->name('pension_report');
    Route::get('add_employee_deduction', 'HumanResourceController@add_employee_deduction')->name('add_employee_deduction');
    Route::get('add_employee_absence', 'HumanResourceController@add_employee_absence')->name('add_employee_absence');
    Route::get('delete_record/{id}/{type}', 'HumanResourceController@delete_record')->name('delete_record');
    Route::post('save_referee', 'EmployeeController@save_referee')->name('save_referee');
    Route::post('update_bio', 'EmployeeController@update_bio_data')->name('update_bio');
    Route::post('change_picture', 'EmployeeController@change_picture')->name('change_picture');
    Route::get('export_payroll/{month}/{year}/{type}/{subsidiary_id}/{advance_user_uri}', 'HumanResourceController@export_payroll')->name('export_payroll');
    Route::post('save_attachment', 'EmployeeController@save_attachment')->name('save_attachment');
    Route::get('delete_experience/{id}', 'EmployeeController@delete_experience')->name('delete_experience');
    Route::get('loan_settlements', 'HumanResourceController@employee_loan_settlements')->name('loan_settlements');
    Route::get('payrolls', 'HumanResourceController@payrolls')->name('payrolls');
    Route::get('leave_types', 'HumanResourceController@leave_types')->name('leave_types');
    Route::get('confirm_payroll/{month}/{year}/{subsidiary_id}/{advance_company_uri}', 'HumanResourceController@confirm_payroll')->name('confirm_payroll');
    // Route::get('employee_leaves', 'HumanResourceController@employee_leaves')->name('employee_leaves');
    Route::match(['get', 'post'], '/employee_leaves', 'HumanResourceController@employee_leaves')->name('employee_leaves');
    Route::get('draft_payrolls', 'HumanResourceController@draft_payrolls')->name('draft_payrolls');
    Route::post('get_payroll', 'HumanResourceController@payrolls')->name('get_payroll');
    Route::get('view/payroll/{id}', 'HumanResourceController@viewPayroll');
    Route::post('add_leave_type', 'HumanResourceController@add_leave_type')->name('add_leave_type');
    Route::get('add_leave_type', 'HumanResourceController@add_leave_type')->name('add_leave_type');
    Route::get('delete_attachment/{id}', 'EmployeeController@delete_attachment')->name('delete_attachment');
    Route::get('download_attachment/{id}', 'EmployeeController@download_attachment')->name('download_attachment');
    Route::get('delete_referee/{id}', 'EmployeeController@delete_referee')->name('delete_referee');
    Route::get('organization/destroy/{id}', 'OrganizationController@destroy');
    Route::resource('employee', 'EmployeeController');
    Route::get('show-employee/{id}/{company_id}', 'EmployeeController@show');
});
//Routes for HR ends


//Routes for Project Manager
Route::group(['middleware' => ['auth','checkPermission:4']],  function() {
    Route::get('projects', 'ProjectsController@projects')->name('projects');
    Route::post('project/issues', 'ProjectsController@issues');
    Route::post('add_project', 'ProjectsController@add_project')->name('add_project');
    Route::get('add_project', 'ProjectsController@add_project')->name('add_project');
    Route::post('update_project', 'ProjectsController@update_project')->name('update_project');
    Route::get('update_project/{id}', 'ProjectsController@update_project')->name('update_project');
});

//Routes for Project Manager ends
Route::resource('hr', 'HumanResourceController');
Route::resource('settings', 'SettingsController');
Route::resource('bank', 'BankController');
Route::resource('country', 'CountryController');
Route::resource('gender', 'GenderController');
Route::resource('organizations', 'OrganizationController');
Route::match(['get', 'post'], '/organizations', 'OrganizationController@index');

// Route::resource('workAddresses', 'WorkAddressController');
Route::match(['get', 'post'], '/workAddresses', 'WorkAddressController@index');
Route::get('/workAddresses/delete/{id}', 'WorkAddressController@destroy');
Route::post('/workAddress/edit', 'WorkAddressController@updateWorkAddress');

// Route::match(['get', 'post'], '/departments', ['uses' => 'DepartmentCon/troller@index']);

Route::resource('departments', 'DepartmentController');


// Route::resource('departments', 'DepartmentController');
Route::resource('grades', 'GradeController');
Route::resource('jobs', 'JobController');
Route::resource('employeeJobs', 'EmployeeJobController');
Route::resource('employeeDepartments', 'EmployeeDepartmentController');
Route::resource('lineManager', 'LineManagerController');
Route::resource('institutions', 'InstitutionController');
Route::resource('institutionDepartments', 'InstitutionDepartmentController');
Route::resource('employeeEducations', 'EmployeeEducationController');
Route::resource('finances', 'FinanceController');
Route::resource('requestCategories', 'RequestCategoryController');
Route::resource('requestItems', 'RequestItemController');
Route::resource('rolePermissions', 'RolePermissionController');
Route::group(['prefix' => 'erp-users'], function() {
    Route::match(['get', 'post'], '/index', ['uses' => 'UserController@create']);
    Route::match(['get', 'post'], '/show', ['uses' => 'UserController@index']);
    Route::get('/destroy/{id}', ['uses' => 'UserController@destroy']);
    Route::get('/activate/{company_id}/{company_uri}/{user_id}', ['uses' => 'UserController@activate']);
    Route::get('/deactivate/{company_id}/{company_uri}/{user_id}', ['uses' => 'UserController@deactivate']);
    Route::post('/update/{id}', ['uses' => 'UserController@update']);
});
Route::get('finance/back', 'FinanceController@goBack');
Route::resource('payables', 'PayablesController');
Route::get('employee/account/{employeeId}', 'UserController@createUserAccountForEmployee');
Route::controller('payables', 'PayablesController');
Route::get('submit/request/{requestGroupId}', 'PayablesController@submitRequest');
Route::get('approve/request/{requestGroupId}', 'PayablesController@');
Route::get('deny/request/{requestGroupId}', 'PayablesController@denyRequest');
Route::post('register/verify/{email}/{token}', 'UserController@verify');

Route::get('register/verify/{email}/{token}', 'UserController@changePassword');
Route::match(['get', 'post'], 'new-request', ['uses' => 'RequestController@create', 'as' => 'new-request']);

Route::resource('menuGroups', 'MenuGroupController');
Route::resource('menus', 'MenuController');

app/Models/Gender.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @SWG\Definition(
 *      definition="Gender",
 *      required={""},
 *      @SWG\Property(
 *          property="code",
 *          description="code",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="name",
 *          description="name",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="created_by",
 *          description="created_by",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="updated_by",
 *          description="updated_by",
 *          type="integer",
 *          format="int32"
 *      )
 * )
 */
class Gender extends Model
{
    use SoftDeletes;

    public $table = 'sys_gender';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'name',
        'created_by',
        'updated_by'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'code' => 'string',
        'name' => 'string',
        'created_by' => 'integer',
        'updated_by' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function employees()
    {
        return $this->hasMany(\App\Models\Employee::class);
    }
}

app/Http/Controllers/GenderController.php
<?php

namespace App\Http\Controllers;

use App\Models\Gender;
use Illuminate\Http\Request;

use App\Http\Requests;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;

class GenderController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $genderCollection = Gender::orderBy('created_at', 'DESC')->get();
        return view('gender.index')->with(['genders'=>$genderCollection]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('gender.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        try{
            $validator = Validator::make($request->all(), [
                'name' => 'required|max:255'
            ]);

            if ($validator->fails()) {
                return back()->withErrors($validator)->withInput();
            }

            //return "here";

            Gender::create([
                'name' => $request->get('name'),
                'created_by'=>Auth::user()->id,
                'updated_by'=>Auth::user()->id
            ]);

            return redirect('gender');

        }catch (\Exception $ex){
            //return $ex->getMessage();
            return back()->withErrors($ex->getMessage())->withInput();
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/gender/create.blade.php
@extends('layouts.app_settings')

@section('page_title')
<h2>Gender</h2>
@endsection

@section('settings_content')
    <section class="content-header">
    </section>
    <div class="content">
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'gender.store']) !!}
                    @if(isset($errors))
                    @if(count($errors) > 0)
                    <div class="alert alert-danger">
                        <ul>
                            @foreach($errors->all() as $error)
                            <li>{{$error}} here</li>
                            @endForeach
                        </ul>
                        @endIf
                    </div>
                    @endIf
                        @include('gender.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/gender/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
   </section>
   <div class="content">
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($gender, ['route' => ['genders.update', $gender->id], 'method' => 'patch']) !!}

                        @include('gender.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/gender/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('gender.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/gender/index.blade.php
@extends('layouts.app_settings')

@section('page_title')
<h2>Gender</h2>
@endsection

@section('settings_content')
    <section class="content-header">
    </section>
    <div class="content">
        <div class="clearfix"></div>

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('gender.table')
            </div>
        </div>
    </div>
@endsection

resources/views/gender/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Gender
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('genders.show_fields')
                    <a href="{!! route('genders.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/gender/show_fields.blade.php
<!-- Code Field -->
<div class="form-group">
    {!! Form::label('code', 'Code:') !!}
    <p>{!! $gender->code !!}</p>
</div>

<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{!! $gender->name !!}</p>
</div>

<!-- Created By Field -->
<div class="form-group">
    {!! Form::label('created_by', 'Created By:') !!}
    <p>{!! $gender->created_by !!}</p>
</div>

<!-- Updated By Field -->
<div class="form-group">
    {!! Form::label('updated_by', 'Updated By:') !!}
    <p>{!! $gender->updated_by !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $gender->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $gender->updated_at !!}</p>
</div>

<!-- Deleted At Field -->
<div class="form-group">
    {!! Form::label('deleted_at', 'Deleted At:') !!}
    <p>{!! $gender->deleted_at !!}</p>
</div>

resources/views/gender/table.blade.php
<table class="table table-responsive" id="genders-table">
    <thead>
        <th>Name</th>
        <th colspan="3">Action</th>
    </thead>
    <tbody>
    @foreach($genders as $gender)
        <tr>
            <td>{!! $gender->name !!}</td>
            <td>
                {!! Form::open(['route' => ['gender.destroy', $gender->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('gender.show', [$gender->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('gender.edit', [$gender->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>